### DISCUSSION TITLE
Where stored 500 Server errors in logs inside azurite?

### DISCUSSION THREAD

**Discussion by Slach** [Azure/Azurite#2455] [Q&A] [answered]
I executed
docker.io/clickhousepro/azurite:latest docker compose service
```
services:
  azure:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    hostname: devstoreaccount1.blob.azure
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30
    command: [ "azurite", "--debug", "/data/debug.log" , "-l", "/data", "--blobHost", "0.0.0.0" ]
    volumes:
      - azure:/data
```

in my e2e scenarios I got following error
```
 2024.08.27 14:55:48.560507 [ 1021 ] {ceb8fa3f-acf5-4c6d-9350-9a645a8cf67b} <Debug>
WriteBufferFromAzureBlobStorage: 
Write at attempt 2 for blob `ufuxgidvjcxyvcgxbrjtymmlizzlxuvu` failed: 500 Internal Server Error
```

I tried `docker compose exec azure cat /data/debug.log`
but I don't see any error message related to the selected time range and related to `ufuxgidvjcxyvcgxbrjtymmlizzlxuvu`

in the stderr/stdout of azure container i see
```
2024.08.27 14:55:48.560507Z azure-1  | 172.18.0.10 - - [27/Aug/2024:14:55:48 +0000] 
"PUT /devstoreaccount1/azure-disk/ufuxgidvjcxyvcgxbrjtymmlizzlxuvu?blockid=uiilnxjafsvefxyzmatgccnosxbawmllkmkfgsdbvjqhiznfeegbforpccciwsrd&comp=block HTTP/1.1" 
500 - 2024
```

How to debug this kind of error?

**Comment by Slach** [comment]
@blueww any suggestion?

why error details doesn't store in debug.log?

in stdout/strerr of container i see
```
[27/Aug/2024:18:07:15 +0000] 
"PUT /devstoreaccount1/azure-disk/awznqgydxphyvfxxmsmdseycxrmegxjf?blockid=xtraofwopvfkhuqshalqqftszdotexfddnnnhzummzydpkploaysgxxmviibdelh&comp=block HTTP/1.1" 500 -
```

but `ls -la /data/debug.log` return
`-rw-r--r--    1 root     root      58433536 Aug 27 18:05 /data/debug.log`

**Comment by blueww** [comment]
@Slach 

Following is my docker-compose.yml file.
The most difference are: 
1. the "command" are different
2. my file mapping the port "10000:10000" , then Azurite can be access from other storage client on same machine outside docker image
3. I map the local folder "C:\temp\azurite\" to "/data" in docker, and save debug log in "/data/debug.log", so the debug log can be accessed on local machine in path "C:\temp\azurite\debug.log".
4. I removed "healthcheck" and "hostname" section in the file, you can add back per your requirement.

```
services:
  azuretablestorage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: always
    command: "azurite --debug /data/debug.log -l /data --blobHost 0.0.0.0"
    volumes:
      - C:\temp\azurite\:/data
    ports:
      - "10000:10000"
      ```
