### ISSUE TITLE
How to assign internal port when running in docker-compose

### ISSUE THREAD

**Issue by KasperPurunen** [Azure/Azurite#122]
Hi.

I'm using docker-compose to run azurite along witha few other services. Since we have large environments that are also using azurite I would like to assign internal ports and expose these but I'm currently unable. When i run 'docker-compose up' azurite only returns an exit code with nothing else to give me a hint of what's wrong. The section in my docker-compose file for azurite is the following:

```
storage-emulator:
    image: arafato/azurite
    volumes:
      - ./external_services/emulator:/opt/azurite/folder
    ports:
      - 20000:20000
    command: ["sh", "--blobPort 20000"]
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
```

Is it even possible to assign another internal port or have I reached a dead end?
