### ISSUE TITLE
Azurite no longer runs correctly as a background task in GitHub Actions

### ISSUE THREAD

**Issue by LarsKemmann** [Azure/Azurite#1271]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.15.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
NPM

### What's the Node.js version?
14.18.2

### What problem was encountered?
I've noticed that, since today, Azurite fails to start correctly in my GitHub Actions pipeline and instead dumps some unknown text/binary content to the GitHub Action log.

Action run before the issue started:
https://github.com/CareTogether/CareTogetherCMS/runs/4710008033?check_suite_focus=true#step:6:6

Action runs showing the issue:
https://github.com/CareTogether/CareTogetherCMS/runs/4755534824?check_suite_focus=true#step:6:6 (first attempt)
https://github.com/CareTogether/CareTogetherCMS/runs/4755601564?check_suite_focus=true#step:6:6 (second attempt)
https://github.com/CareTogether/CareTogetherCMS/runs/4755632933?check_suite_focus=true#step:6:6 (third attempt, reverting my .NET SDK upgrade to try to make the Action environment as identical to the previous successful run as possible)

### Steps to reproduce the issue?
See above. It seems like the following YAML is problematic now, but wasn't as of two days ago.
```yaml
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install Azurite storage emulator
      run: npm install -g azurite
    - name: Start Azurite blob endpoint
      shell: bash
      run: azurite-blob &
```

### Have you found a mitigation/solution?
No. I can't figure out what is going on that might be affecting this. (On a related note, it would be helpful if there was some guidance provided by the Azurite GitHub readme/wiki for how to use Azurite in a GitHub Action "properly", if the above is improper somehow. I got this to work based on [guidance in an issue I found in the Azurite project](https://github.com/Azure/Azurite/issues/451#issuecomment-639398801) some time back provided by @ethomson.)
