### ISSUE TITLE
How do i use Azurite Blob Storage using Python ?

### ISSUE THREAD

**Issue by 4vadim4** [Azure/Azurite#1307]
i use docker-compose for launch container with app, DB and Azurite:

```
version: '3.8'

services:
  api:
    # app part here

  db:
    # db part here

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    volumes:
      - ./cert/azurite:/azurite_data
    command: "azurite --blobHost 127.0.0.1 --blobPort 10000"
    ports:
      - "10000:10000"
    restart: always
    networks:
      - net
```

   now i have a three containers and i'm trying to teach docker container with app on `Python3.10` uploads, gives and deletes `blob-data` in another docker container with `Azurite`,
  how i can do it ? what libraries should i use on the python-app container side for connect to azurite container ?
