### ISSUE TITLE
Microsoft Azure Storage Explorer is "Unable to retrieve child resources" while connection with Azurite under Docker Compose is established

### ISSUE THREAD

**Issue by sk0va** [Azure/Azurite#1615]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
latest

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
N/A

### What problem was encountered?
Microsoft Azure Storage Explorer is "Unable to retrieve child resources" while connection with Azurite under Docker Compose is established

### Steps to reproduce the issue?
1. Run docker compose (Windows 10, Docker version 20.10.13 on linux containers) with next configuration
```
version: "3.9"
services:
  blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    environment:
      - AZURITE_ACCOUNTS="devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
    command: azurite-blob --blobHost 0.0.0.0 --skipApiVersionCheck --disableProductStyleUrl
```
2. Wait for the output 
```
[+] Running 1/0
 - Container docker-blob-storage-1  Created                                                                                                                                     0.0s 
Attaching to docker-blob-storage-1
docker-blob-storage-1  | Azurite Blob service is starting on 0.0.0.0:10000
docker-blob-storage-1  | Azurite Blob service successfully listens on http://0.0.0.0:10000
```
3. Run Microsoft Azure Storage Explorer (version 1.24.3)
4. Create new connection using one of next methods:
   4.1 By choosing "Local storage emulator" with default configuration
   4.2 By choosing "Storage account or service" and specifying next connection string:
```
DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1
```
5. In logs of the Azure Storage Explorer message "Successfully added new connection" appears
6. Try to expand Blob Containers. It will return message like
``` 
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "Invalid storage account.\nRequestId:.....
 ```
A docker compose output will be like
```
docker-blob-storage-1  | 172.18.0.1 - - [26/Jul/2022:10:16:57 +0000] "GET /devstoreaccount1?comp=properties&restype=account HTTP/1.1" 400 -
docker-blob-storage-1  | 172.18.0.1 - - [26/Jul/2022:10:16:57 +0000] "GET /devstoreaccount1?comp=list&include=metadata HTTP/1.1" 400 -
docker-blob-storage-1  | 172.18.0.1 - - [26/Jul/2022:10:16:57 +0000] "GET /devstoreaccount1?comp=list&include=metadata&timeout=30 HTTP/1.1" 400 -
docker-blob-storage-1  | 172.18.0.1 - - [26/Jul/2022:10:16:59 +0000] "GET /devstoreaccount1?comp=list&include=metadata HTTP/1.1" 400 -
docker-blob-storage-1  | 172.18.0.1 - - [26/Jul/2022:10:16:59 +0000] "GET /devstoreaccount1?restype=service&comp=properties HTTP/1.1" 400 -
docker-blob-storage-1  | 172.18.0.1 - - [26/Jul/2022:10:17:37 +0000] "PUT /devstoreaccount1/one?restype=container HTTP/1.1" 400 -
```
### Have you found a mitigation/solution?
Nope. I don't know the reason of such behavior or how to make it works. Please help!
