### ISSUE TITLE
Azurite in docker | Durable functions do not authenticate - Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

### ISSUE THREAD

**Issue by CarlosGomesMarel** [Azure/Azurite#1884]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
mcr.microsoft.com/azure-storage/azurite:latest

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
v18.2.0, but not used for docker version.

### What problem was encountered?
Azure Functions Durable Functions do not authenticate with Durable Functions in the .NET isolated worker - azure function.
See https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-isolated-overview .

```
General error: Failed to create the task hub: DurableTask.AzureStorage.Storage.DurableTaskStorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
 ---> Microsoft.WindowsAzure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.CreateIfNotExistsAsync(TableRequestOptions requestOptions, OperationContext operationContext, CancellationToken cancellationToken)
   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, AzureStorageOrchestrationServiceSettings settings, Func`3 operation, AzureStorageOrchestrationServiceStats stats, String clientRequestId) in /_/src/DurableTask.AzureStorage/TimeoutHandler.cs:line 133
   at DurableTask.AzureStorage.Storage.AzureStorageClient.MakeStorageRequest[T](Func`3 storageRequest, String accountName, String operationName, String clientRequestId, Boolean force) in /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs:line 136
Request Information
RequestID:2a6b23bf-f002-00be-317c-62235d000000
RequestDate:Wed, 29 Mar 2023 13:22:06 GMT
StatusMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ErrorCode:AuthenticationFailed
ErrorMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

### Steps to reproduce the issue?

Spin up azurite using docker-compose

```
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
```

- Launch Isolated worker Azure Function with Durable functions
*local.settings.json*
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",

Azure function will not be able to start the durable function.

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by blueww** [comment]
@CarlosGomesMarel 

For the request ID "2a6b23bf-f002-00be-317c-62235d000000", it looks is from product Azure , instead of Azurite.
Would you please check?

Besides that, we are not Azure function  expert, so might not be the best person to look the   Azure function  error. 
If need Azurite team support, would you please give the Azurite debug log for the request which the responds is not expected?

**Comment by CarlosGomesMarel** [comment]
Found a fix.  Specified **--loose** and it works now.
`--loose enables loose mode which ignore unsupported headers and parameters.`

```
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    volumes:
       - azurite_data:/data
    command: azurite --loose -l /data --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
    ports:
       - '10000:10000'
       - '10001:10001'
       - '10002:10002'
```
