### ISSUE TITLE
Can not Stream large File to Azure Blob Storage (Azurite)

### ISSUE THREAD

**Issue by git9999999** [Azure/Azurite#1998]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
The latest available in DockerHub
b6004981581903cd47acd493a5d0077b9750f94f7a7b6e4f42f0eb79d623e15e

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
I don't understand this question.

### What problem was encountered?
I can not stream files that are larger than 250MB to azure. If i try too, the transmission will stuck. 
I can stream with the same code to the file system any size. 
For me it looks like a Azure bug. I opened a Ticket with Microsoft, but they send me here as is use Azurite. 
Please checkout the attached Project and README.md. There you see how to reproduce this bug.

### Steps to reproduce the issue?
I attache a working java app. See README.md

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:
```
-d "<pathtodebuglog>"
```
This may be possible, see docker-compose file in the example project. Maybe you can tell me where to put this in the docker-compose file.

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No

**Comment by git9999999** [comment]
[azure-blobstoreage-large-file-problem (3).zip](https://github.com/Azure/Azurite/files/11662691/azure-blobstoreage-large-file-problem.3.zip)

**Comment by blueww** [comment]
@git9999999 

Would you please confirm for "can not stream files that are larger than 250MB to azure", do you stream it to product Azure , or to Azurite? 

If to Azurite, would you please share the Azurite debug log? (hide credential)

**Comment by git9999999** [comment]
@blueww please can you tell me how to enable the debug log my docker-compose file?

**Comment by blueww** [comment]
You can use a docker-compose file like following.
Please note, it will mount a local folder "c:/azurite" to "/workspace", and save the debug log to "/workspace/debug.log". So you will find the debug log in local path "c:/azurite/debug.log"

```
version: "3.9"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite    
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    environment:
      - AZURITE_ACCOUNTS=localdevsa001:cGFzc3dvcmQ=;local-dev-sa-003:cGFzc3dvcmQ=;
    command: azurite -l /workspace -d /workspace/debug.log --blobPort 10000 --blobHost 0.0.0.0 --queuePort 10001 --queueHost 0.0.0.0 --tablePort 10002 --tableHost 0.0.0.0
    volumes: 
      - c:/azurite:/workspace
```

**Comment by git9999999** [comment]
Hi

I changed the docker-compose file from
```
version: "4"
services:

  ms-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    environment:
      - AzureWebJobsStorage="UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://host.docker.internal"

```

to

```
version: "4"
services:

  ms-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    environment:
      - AZURITE_ACCOUNTS=localdevsa001:cGFzc3dvcmQ=;local-dev-sa-003:cGFzc3dvcmQ=;
    command: azurite -l /workspace -d /workspace/debug.log --blobPort 10000 --blobHost 0.0.0.0 --queuePort 10001 --queueHost 0.0.0.0 --tablePort 10002 --tableHost 0.0.0.0
    volumes:
      - c:/develop/azurite:/workspace
```
Azurlite starts, see the log
[debug.log](https://github.com/Azure/Azurite/files/11672572/debug.log)

But my App can not connect to it.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'azureBlobBugDownloaderController' defined in com.azureproblem.blob.MsGeneralMockConfiguration: Failed to instantiate [com.azureproblem.blob.controller.AzureBlobBugDownloaderController]: Factory method 'azureBlobBugDownloaderController' threw exception with message: Status code 404, "<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>ResourceNotFound</Code>
  <Message>The specified resource does not exist.
RequestId:86cbc58d-d5dc-4a4a-b20f-5f266e5558a2
Time:2023-06-07T04:45:49.541Z</Message>
</Error>"
```

Here is my Spring config
```
server:
  port: 8544
  tomcat:
    connection-timeout: 30m
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
      enabled: true
  cloud:
    azure:
      storage:
        blob:
          connection-string: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
```

I guess with with the change in the docker-compose we lost the `devstoreaccount1`?
