### ISSUE TITLE
Question: unable to set Azurite CORS rules

### ISSUE THREAD

**Issue by arashcomsense** [Azure/Azurite#2051]
What is the exact Azurite CLI command to issue to set its CORS rules similar to the following screenshot in a docker compose file? I issued `azurite --loose` command but it was not conclusive.

```yml
storageemulator:
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    command: "azurite --loose"  # This command does not solve the CORS problem I am having.
    container_name: myemulator
```

![image](https://github.com/Azure/Azurite/assets/72229415/c164d416-e143-457f-9e92-639d67ea4571)
