### ISSUE TITLE
Uploading files on my local environment

### ISSUE THREAD

**Issue by silcki** [Azure/Azurite#2326]
### Which service(blob, file, queue, table) does this issue concern?
Azure Blob

### Which version of the Azurite was used?
3.28.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
mcr.microsoft.com/azure-storage/azurite

### What's the Node.js version?
14.21.3 (inside the image)

### What problem was encountered?
I'm trying to set up my local environment for development because all our projects are migrating to the Azure Cloud, and I faced an issue where I can't upload any file to Azurite.
The local environment based on docker images:
* PHP-FPM 8.1
* Nginx
* Craft CMS

```
version: "3.9"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30
    entrypoint: ["azurite", "--blobHost", "0.0.0.0", "--blobPort", "10000","-l", "data"]
    ports:
      - "10000:10000"
    environment:
      - AZURITE_CONNECTION_STRING=${ASSETS_CONNECTION_STRING}
      - AZURITE_BLOB_ENDPOINT=${ASSETS_BASE_URL}
    networks:
      - 'myprj'
    volumes:
      - ./docker/blob-storage:/opt/azurite/data

networks:
  myprj:
    name: myprj
    external: true
```
the .env
```
ASSETS_BASE_URL=http://azurite:10000/local-images
ASSETS_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=local-images;AccountKey=myaccountkey;BlobEndpoint=http://azurite:10000;
```
The list of issues is as follows:
* when I try to get a list of the containers, I receive a response that the parameter comp=list has a wrong value
```
Value for one of the query parameters specified in the request URI is invalid.
RequestId:ec1d3ffa-c126-4bbf-89a2-ce55e8b1b2ed
Time:2023-12-11T21:17:25.133Z
ErrorCode:InvalidQueryParameterValue
```
It works when I try to make the same request to Azure Blob in the Azure Cloud.

* I assumed that when the Azurite runs, it doesn't create a container, and I decided to do that manually by Azure CLI
```
  storage_init:
    image: mcr.microsoft.com/azure-cli:latest
    command:
      - /bin/sh
      - -c
      - |
        az storage container create --name local-images
    networks:
      - 'myprj'
    depends_on:
      azurite:
        condition: service_healthy
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ${ASSETS_CONNECTION_STRING}
```
but it didn't help and I've tried to do the same inside the Azure CLI container but got the error
```bash
$ az storage container create --name local-images --connection-string "DefaultEndpointsProtocol=http;AccountName=local-images;AccountKey=myaccountkey;BlobEndpoint=http://azurite:10000"
```
```
Unexpected return type <class 'str'> from ContentDecodePolicy.deserialize_from_http_generics.
Bad Request
ErrorCode:None
```

**Comment by EmmaZhu** [comment]
Hi @silcki ,

Can you get the debug log for Azurite to help to us on investigation? https://github.com/azure/azurite#debug-log-configuration

Thanks
Emma

**Comment by silcki** [comment]
Hi @EmmaZhu 
Thank you for taking the time to look at my question.
[debug.log](https://github.com/Azure/Azurite/files/13658852/debug.log)
This log contains:
- init logs
- the attempt to create a container by Azure CLI docker container
- the attempt to get the list of containers in the Craft CMS admin panel
- the attempt to upload one file to the container

**Comment by EmmaZhu** [comment]
Hi @silcki ,

From the log you shared, seems you want to use `azurite` as hostname and `local-images` as storage account name. 

But the SDK uses `http://azurite/local-images` as URL to container:
`RequestMethod=PUT`` RequestURL=http://azurite/local-images?restype=container`

Seems the endpoint in your connection string points to host. The endpoint in storage should point to the account.

Can you have a try with following connection string: 
`DefaultEndpointsProtocol=http;AccountName=local-images;AccountKey=myaccountkey;BlobEndpoint=http://azurite:10000/local-images`


Thanks
Emma

**Comment by silcki** [comment]
Hi @EmmaZhu 
Yes, you are right. Your suggestion helped me (I thought I tried all possible ways). But this was half of the solution, Azurite doesn't create a container automatically, and for that, I need to use Azure CLI.
```
version: "3.9"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30
    entrypoint: ["azurite", "--blobHost", "0.0.0.0", "--blobPort", "10000","-l", "data", "-d", "/var/log/debug.log"]
    ports:
      - "10000:10000"
    environment:
      - AZURITE_CONNECTION_STRING=${ASSETS_CONNECTION_STRING}
      - AZURITE_BLOB_ENDPOINT=${ASSETS_BASE_URL}
      - AZURITE_ACCOUNTS=${AZURITE_ACCOUNTS}
    networks:
      - 'ipgx'
    volumes:
      - ./docker/azurite/blob-storage:/opt/azurite/data
      - ./docker/azurite/log:/var/log

  storage_init:
    image: mcr.microsoft.com/azure-cli:latest
    command:
      - /bin/sh
      - -c
      - |
        az storage container create -n local-images && \
        az storage container set-permission -n local-images --public-access blob && \
        az storage container set-permission -n local-images --public-access container
    networks:
      - 'ipgx'
    depends_on:
      azurite:
        condition: service_healthy
    tty: true
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ${ASSETS_CONNECTION_STRING}

networks:
  ipgx:
    name: ipgx
    external: true
```

.env
```
ASSETS_BASE_URL=http://azurite:10000/local-images
ASSETS_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=local-images;AccountKey=myaccountkey;BlobEndpoint=http://azurite:10000/local-images;
ASSETS_CONTAINER=local-images
AZURITE_ACCOUNTS="local-images:myaccountkey"
```

But now I face another issue: when I try to get the uploaded image, I receive an Authorization Failure exception (by default, a container is created as a private). I added the lines of CLI on init but it did'n help.
```
 - /bin/sh
      - -c
      - |
        az storage container create -n local-images && \
        az storage container set-permission -n local-images --public-access blob && \
        az storage container set-permission -n local-images --public-access container
```
The image URL
`http://azurite:10000/local-images/images/SCJ-Image-for-BG-website-1-scaled.jpg`
[debug.log](https://github.com/Azure/Azurite/files/13766882/debug.log)
