### ISSUE TITLE
Docker image won't stop restarting

### ISSUE THREAD

**Issue by bison92** [Azure/Azurite#2438]
### Which service(blob, file, queue, table) does this issue concern?

Docker version of Azurite

### Which version of the Azurite was used?

latest- just pulled from registry. mcr.microsoft.com/azure-storage/azurite                      latest    d9dc9980c4d0 

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

mcr.microsoft.com

### What's the Node.js version?

docker.

### What problem was encountered?

Container won't run and only restarts outputting this line: 

`Exit due to unhandled error: unsupported`

### Steps to reproduce the issue?

I'm running the image with the following docker-compose : 

```yaml

  azuretablestorage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    restart: always
    command: "azurite --blobPort ${AZURITE_PORT_PREFIX}00 --queuePort ${AZURITE_PORT_PREFIX}01 --tablePort ${AZURITE_PORT_PREFIX}02 --blobHost 0.0.0.0 --tableHost 0.0.0.0 --queueHost 0.0.0.0 --cert /https/aspnetapp.pfx --pwd 123123"
    volumes:
      - ${HTTPS_LOCATION}/servicehub.pfx:/https/aspnetapp.pfx:ro
    ports:
      - "${AZURITE_PORT_PREFIX}00:${AZURITE_PORT_PREFIX}00"
      - "${AZURITE_PORT_PREFIX}01:${AZURITE_PORT_PREFIX}01"
      - "${AZURITE_PORT_PREFIX}02:${AZURITE_PORT_PREFIX}02"
    networks:
      - netBackEnd
```

I tried adding a volume and the -d parameter, pointing to a file there, but it still fails with the same error and no debug file is created.

### Have you found a mitigation/solution?

No solution yet, except to use some other flavor outside docker.

**Comment by blueww** [comment]
@bison92 

I can't repro this issue.
I tested with following docker-compose.yml file, and it works well on my machine with latest Azurite docker image.
```
services:
  azuretablestorage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    restart: always
    command: "azurite --blobPort 10000 --queuePort 10001 --tablePort 10002 --blobHost 0.0.0.0 --tableHost 0.0.0.0 --queueHost 0.0.0.0 --cert /https/cert123456.pfx --pwd 123456"
    volumes:
      - C:\temp\azurite\cert123456.pfx:/https/cert123456.pfx:ro
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
 ```
Please note,
1. I added "services:" in the first line, or the `docker compose up` command will fail on my machine with " (root) Additional property azuretablestorage is not allowed".
2. I removed the networks netBackEnd, since netBackEnd is not on my machine
3. I don't use the parameters to input the port and file location. 

However, all these difference are not related with Azurite itself. Please check if you have any wrong configuration on your machine or docker compose file.
