### ISSUE TITLE
Azure Shared Access Signature - Signature did not match using ingress nginx

### ISSUE THREAD

**Issue by rlugovyy** [Azure/Azurite#2448]
I have problems connecting to azure.blob.storage using ingress as a proxy to have 1 entry point for my app. When I try to connect directly, everything works, while through ingress I get an error: Connection to Azure Blob Storage failed! Reason is: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

```
this.aborterController = new AbortController(); 
this.sharedKeyCredential = new AzureStorage.StorageSharedKeyCredential(  
  getFileStorageBlobDbConfigs().storageName,     
  getFileStorageBlobDbConfigs().key1,     
);
this.blobServiceClient = new AzureStorage.BlobServiceClient(        
  `https://${getFileStorageBlobDbConfigs().storageName}.blob.core.windows.net\`,
  AzureStorage.newPipeline(this.sharedKeyCredential),
);

this.sharedKeyCredential = new AzureStorage.StorageSharedKeyCredential(
  getFileStorageBlobDbConfigs().storageName,
  getFileStorageBlobDbConfigs().key1,
);
this.blobServiceClient = new AzureStorage.BlobServiceClient(
  'https://my.ingress.com/blobstorage/',
  AzureStorage.newPipeline(this.sharedKeyCredential),
);
// check 
try {
  await new AzureBlobStorage().checkConnection();
} catch (error) {
  Logger.error(`Connection to Azure Blob Storage failed! Reason is: ${(error as { message: string }).message}`);
}
```

and here is my ingress (also in this cluster works istio if it is important)

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: $1
    nginx.ingress.kubernetes.io/upstream-vhost: teststorage8297.blob.core.windows.net
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: proxy-to-blob-storage-ingress
  namespace: default
  spec:
    ingressClassName: nginx
    rules:
    - host: my.ingress.com
      http:
        paths:
        - backend:
           service:
             name: proxy-to-blob-storage
             port:
               number: 443
             path: /blobstorage(.\*)
             pathType: Prefix
    tls:
    - hosts:
      - my.ingress.com
      secretName: proxy-to-blob-storage-tls\`
// service
apiVersion: v1
kind: Service
metadata:
  name: proxy-to-blob-storage
  namespace: default
spec:
  type: ExternalName
  externalName: teststorage8297.blob.core.windows.net
  ports:
    - port: 443
```

I have only been able to connect and send a file via curl so far

```
curl -X PUT -d "file content" -H "x-ms-blob-type: BlockBlob" "https://my.ingress.com/blobstorage/test/test.txt?SAS-Token"
```
