### ISSUE TITLE
Blob in docker can't persist to docker volume

### ISSUE THREAD

**Issue by jhuang-simwell** [Azure/Azurite#2469]
### Which service(blob, file, queue, table) does this issue concern?

Blob

### Which version of the Azurite was used?

3.32.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub

### What's the Node.js version?

v20.10.0

### What problem was encountered?

``` yml
    local_dev_azurite:
        platform: ${PLATFORM}
        image: mcr.microsoft.com/azure-storage/azurite
        hostname: azurite
        command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000"
        ports:
            - "10000:10000"
        volumes:
            - /d/az/data:/data
```

### Steps to reproduce the issue?

1. start the docker;
2. upload file to blob with Java SDK;
3. the returned url is abled to download the file;
4. but not file in the /data

### Have you found a mitigation/solution?

no
