### ISSUE TITLE
Have to repeat container name in blob name

### ISSUE THREAD

**Issue by peinearydevelopment** [Azure/Azurite#2524]
I have a Windows machine with WSL installed and Ubuntu 22.04 installed. I'm running Azurite in a container via Docker compose. My docker-compose.yml is as follows:
```
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace --debug /workspace/debug.log"
    ports:
      - 10010:10000
      - 10011:10001
      - 10012:10002
    volumes:
      - ./azurite:/workspace
```

I created the following console(c#) application to test a blob upload to this Azurite instance:
```
using Azure.Storage.Blobs;

var bsc = new BlobServiceClient("AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;AccountName=devstoreaccount1;BlobEndpoint=http://host.docker.internal:10010/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10011/devstoreaccount1;TableEndpoint=http://host.docker.internal:10012/devstoreaccount1;");

var bcc = bsc.GetBlobContainerClient("container");
await bcc.CreateIfNotExistsAsync();

try
{
    var bc = bcc.GetBlobClient("test.txt");
    await bc.UploadAsync(BinaryData.FromObjectAsJson(new { Hello = "World" }));
}
catch (Exception e)
{
    /*
        The specified resource name contains invalid characters.
        RequestId:717cfd7d-4e3a-48b1-aa88-7e39184e3c2a
        Time:2025-01-08T04:10:30.514Z
        Status: 400 (The specified resource name contains invalid characters.)
        ErrorCode: InvalidResourceName

        Content:
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <Error>
          <Code>InvalidResourceName</Code>
          <Message>The specified resource name contains invalid characters.
        RequestId:717cfd7d-4e3a-48b1-aa88-7e39184e3c2a
        Time:2025-01-08T04:10:30.514Z</Message>
        </Error>

        Headers:
        Server: Azurite-Blob/3.33.0
        x-ms-error-code: InvalidResourceName
        x-ms-request-id: 717cfd7d-4e3a-48b1-aa88-7e39184e3c2a
        Date: Wed, 08 Jan 2025 04:10:30 GMT
        Connection: keep-alive
        Keep-Alive: REDACTED
        Transfer-Encoding: chunked
        Content-Type: application/xml
     */
}

var bc2 = bcc.GetBlobClient("container/test2.txt");
await bc2.UploadAsync(BinaryData.FromObjectAsJson(new { Hello = "World" }));
```

When the application tries to create the first blob, it throws the exception shown in the comments. The second blob will get created:![Image](https://github.com/user-attachments/assets/2dee6394-7562-4fc6-8bad-e8d8425ac925)

This same code though, running against a Storage Account in Azure creates both files though as follows:![Image](https://github.com/user-attachments/assets/343ead61-be57-4740-982d-c9b0ad158653)

At the moment, I have code checking if the BlobServiceClient Uri contains "host.docker.internal" or "localhost" and then adding the container name to the blob name to work around this issue.

Is there a different way I should be creating my clients or is this a bug in Azurite?

Thanks!
