### ISSUE TITLE
errors using --loose in docker-compose 

### ISSUE THREAD

**Issue by duranmg** [Azure/Azurite#381]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
latest

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
docker pull mcr.microsoft.com/azure-storage/azurite

### What problem was encountered?
When trying to run with --loose I get an error.

docker-compose.yml 
  azure_storage_emulator:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: always
    command: "--loose"
    ports:
      - "10001:10001"
      - "10000:10000"

I get this error: 

Creating azurite ... error                                                                                                                                          
ERROR: for azurite  Cannot start service azure_storage_emulator: b'OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \\"--loose\\": executable file not found in $PATH": unknown'

ERROR: for azure_storage_emulator  Cannot start service azure_storage_emulator: b'OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \\"--loose\\": executable file not found in $PATH": unknown'
ERROR: Encountered errors while bringing up the project.

### Steps to reproduce the issue?

run above using 
docker-compose up 

### Have you found a mitigation/solution?
no.  just to not use --loose .  but then i get errors in my service that say to use --loose.

**Comment by XiaoningLiu** [comment]
How about this `command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --loose"`?

**Comment by duranmg** [comment]
Yes!  Thanks that worked.

**Comment by hansmbakker** [comment]
@XiaoningLiu according to https://stackoverflow.com/questions/37366857/how-to-pass-arguments-to-entrypoint-in-docker-compose-yml it seems easier if Azurite's Dockerfile would use an `entrypoint` item, so that we would only need to specify additional parameters in the `command` item.

What do you think?

**Comment by XiaoningLiu** [comment]
Hi @hansmbakker I think you are right. Re-open this issue for tracking.

**Comment by djangofan** [comment]
Based on original question in this thread, this worked for me:
```
version: '2'
services:
  azure_storage_emulator:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: always
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    ports:
      - "10001:10001"
      - "10000:10000"
```
