### ISSUE TITLE
I can't seem to set a valid storage account/key pair with "AZURITE_ACCOUNTS".

### ISSUE THREAD

**Issue by carlosonunez** [Azure/Azurite#411]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the Azurite was used?

3.5.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Docker

### What's the Node.js version?

v10.19.0

### What problem was encountered?

I tried to set `AZURITE_ACCOUNTS` as an environment variable per the code snippet shown below but keep getting `Invalid storage account` errors with no debug output.

#### Error

It also seems as if this error does not honor `AZURE_CORE_OUTPUT`:

```xml
Invalid storage account. ErrorCode: InvalidOperation
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>InvalidOperation</Code>
  <Message>Invalid storage account.
RequestId:8da87005-da4c-40ce-9e61-1ebbb41297e7
Time:2020-02-27T00:21:21.139Z</Message>
</Error>
```

#### Code Snippet

```yaml
services:
  local-azure:
    image: mcr.microsoft.com/azure-storage/azurite
  blobstore:
    extends: local-azure
    entrypoint: azurite-blob
    environment:
      - AZURITE_ACCOUNTS="testaccount:test"
    ports:
      - 10000:10000
    command:
      - -d
      - debug.log
      - --blobHost
      - 0.0.0.0
      - --blobPort
      - "10000"
```

### Steps to reproduce the issue?

1. Create a `docker-compose.yaml` file and add the above code snippet into it.
2. Start blobstore: `docker-compose up -d blobstore`
3. Run this: `az storage container list --connection-string "DefaultEndpointsProtocol=http;AccountName=testaccount;AccountKey=test;BlobEndpoint=http://blobstore:10000/testaccount"`

### Have you found a mitigation/solution?

Keep using the default account/key pair.
