### ISSUE TITLE
Container not found error on specific cases

### ISSUE THREAD

**Issue by cybercop** [Azure/Azurite#543]
Here is my docker -compose file

```
version: "3.4"

services:

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    networks:
      - my-network
    container_name: Storage.Azurite
    ports:
      - 10000:10000

  filestorageapi:
    image: ${REGISTRY:-storage}/filestorageapi:${PLATFORM-linux}-${TAG:-latest}
    container_name: FileApi
    build:
      context: .
      dockerfile: FileStorage/Api/FileApi/Dockerfile
    networks:
      - my-network
    depends_on:
      - azurite

networks:
  my-network:

```

Here is part of my c# code

```
var containerClient = _blobServiceClient.GetBlobContainerClient("company");
await containerClient.CreateIfNotExistsAsync().ConfigureAwait(false);

var blobClient = containerClient.GetBlobClient(uniqueFileName);

var result = await blobClient.UploadAsync(formFile.OpenReadStream());
var fileInfo = new FileInfoResponse(uniqueFileName, result.Value.VersionId, result.Value.ETag, result.Value.ContentHash,
                        result.Value.LastModified);

return Result.Ok(fileInfo);
```

Connection string used:
`      ConnectionString =       "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://Storage.Azurite:10000/devstoreaccount1;";`

When i run the application in debug mode 
`await containerClient.CreateIfNotExistsAsync().ConfigureAwait(false);`
runs successfully but,
`var result = await blobClient.UploadAsync(formFile.OpenReadStream());`
fails. And the error says container not found, which is kind of weird because the code to create container ran successfully.

If i run azurite in docker with following command:
`docker run -p 10000:10000 -p 10001:10001 mcr.microsoft.com/azure-storage/azurite
`
and run the api in iis with following connection string
`ConnectionString =          "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;";`

I am successfully able to upload files.

Any reason why this happens?
