### ISSUE TITLE
Helm chart?

### ISSUE THREAD

**Issue by justinmchase** [Azure/Azurite#968]
I see the Docker container, is there a Helm chart somewhere too?

**Comment by justinmchase** [comment]
For posterity sake I made this pretty easily which seems to do the trick!

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  namespace: docs
spec:
  selector:
    matchLabels:
      component: azurite
  replicas: 1
  template:
    metadata:
      labels:
        component: azurite
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite
          imagePullPolicy: IfNotPresent
          command:
            - azurite
            - -l
            - /data
            - --blobHost
            - "0.0.0.0"
            - --queueHost
            - "0.0.0.0"
            - --tableHost
            - "0.0.0.0"
            - --loose
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: $PWD/.data/azurite
---
kind: Service
apiVersion: v1
metadata:
  name: azurite
  namespace: docs
spec:
  selector:
    component: azurite
  ports:
    - name: blob
      protocol: TCP
      port: 10000
      targetPort: 10000
    - name: queue
      protocol: TCP
      port: 10001
      targetPort: 10001
    - name: table
      protocol: TCP
      port: 10002
      targetPort: 10002
```

Deploy it with:
```sh
envsubst < local.yaml | kubectl apply -f -
```
